name: Test Obfuscation Tool

on:
  workflow_dispatch:

jobs:
  explore-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Prepare Test APK
        run: |
          echo "Dummy APK Content" > app-test.apk

      # تشغيل الأداة مباشرة من Docker Hub واستعراض كود المساعدة (Help)
      - name: Run Obfuscapk Container
        run: |
          docker run --rm claudiugeorgiu/obfuscapk --help
